server:
  port: ${API_GATEWAY_SERVER_PORT:8888}

app:
  api-prefix: /api
  services:
    identity-base-url: ${IDENTITY_SERVICE_CONTEXT_URL:http://localhost:9090/identity}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:64988}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity_service
              uri: ${IDENTITY_SERVICE_URL:http://localhost:9090}
              predicates:
                - Path=${app.api-prefix}/identity/**
              filters:
                - StripPrefix=1

            - id: profile_service
              uri: ${PROFILE_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=${app.api-prefix}/profile/**
              filters:
                - StripPrefix=1

            - id: post_service
              uri: ${POST_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=${app.api-prefix}/post/**
              filters:
                - StripPrefix=1

            - id: file_service
              uri: ${FILE_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=${app.api-prefix}/file/**
              filters:
                - StripPrefix=1
